apiVersion: v1
kind: Service
metadata:
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health/readiness
    alb.ingress.kubernetes.io/success-codes: 200-399
  labels:
    app.kubernetes.io/name: spring-petclinic
  name: spring-petclinic
spec:
  ports:
    - name: service
      port: 80
      protocol: TCP
      targetPort: 28080
  selector:
    app.kubernetes.io/name: spring-petclinic
  type: ClusterIP
