apiVersion: kustomize.config.k8s.io/v1beta1
images:
- name: 318564120968.dkr.ecr.ap-northeast-2.amazonaws.com/cps/spring-petclinic
  newTag: 3.0.2-SNAPSHOT
kind: Kustomization
namespace: yongjoon
replicas:
- count: 2
  name: spring-petclinic
resources:
- ../../base
patches:
- path: PatchDeployment.yaml
  target:
    kind: Deployment
    name: spring-petclinic
    version: v1
- path: PatchServiceAccount.yaml
  target:
    kind: ServiceAccount
    name: spring-petclinic
    version: v1
