# To track versions in Datadog
- op: replace
  path: /spec/template/metadata/labels/app.kubernetes.io~1version
  value: 3.0.1

# JAVA_TOOL_OPTIONS
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: JAVA_TOOL_OPTIONS
    #value: "-Dspring.profiles.active=prod -XX:+UseG1GC -XX:ActiveProcessorCount=2 -XX:InitialRAMPercentage=70.0 -XX:MaxRAMPercentage=70.0 -javaagent:/usr/local/bin/dd-java-agent.jar"
    value: "-Dspring.profiles.active=dev -XX:ActiveProcessorCount=2 -XX:InitialRAMPercentage=70.0 -XX:MaxRAMPercentage=70.0"

# Datadog
#- op: add
#  path: /metadata/labels/tags.datadoghq.com~1env
#  value: eks_prod
#- op: add
#  path: /spec/template/metadata/labels/tags.datadoghq.com~1env
#  value: eks_prod
#- op: add
#  path: /spec/template/metadata/labels/app.kubernetes.io~1env
#  value: eks_prod

# nodeAffinity
#- op: replace
#  path: /spec/template/spec/affinity/nodeAffinity/requiredDuringSchedulingIgnoredDuringExecution/nodeSelectorTerms/0/matchExpressions/0/values/0
#  value: spot

# Resources
- op: replace
  path: /spec/template/spec/containers/0/resources
  value:
    limits:
      memory: "1Gi"
    requests:
      cpu: "2000m"
      memory: "1Gi"
